//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_LANGUAGE
    {
        public ADDITIONAL_LANGUAGE()
        {
            this.BEACHED_LANGUAGE = new HashSet<BEACHED_LANGUAGE>();
        }
    
        public int LANG_ID { get; set; }
        public string LANG_NAME { get; set; }
    
        public virtual ICollection<BEACHED_LANGUAGE> BEACHED_LANGUAGE { get; set; }
    }
}
