//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_TECHNOLOGY
    {
        public ADDITIONAL_TECHNOLOGY()
        {
            this.BEACHED_ADDITIONAL_TECHNOLOGY = new HashSet<BEACHED_ADDITIONAL_TECHNOLOGY>();
        }
    
        public int TECH_ID { get; set; }
        public string TECH_NAME { get; set; }
    
        public virtual ICollection<BEACHED_ADDITIONAL_TECHNOLOGY> BEACHED_ADDITIONAL_TECHNOLOGY { get; set; }
    }
}
