//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEACHED_LANGUAGE
    {
        public long BEACHED_ID { get; set; }
        public int LANG_ID { get; set; }
        public byte FLUENCY { get; set; }
    
        public virtual ADDITIONAL_LANGUAGE ADDITIONAL_LANGUAGE { get; set; }
        public virtual BEACHED BEACHED { get; set; }
    }
}
