//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEACHED_IN_HOUSE_TECHNOLOGY
    {
        public int BIHT_ID { get; set; }
        public long BEACHED_ID { get; set; }
        public int TECH_ID { get; set; }
        public byte TECH_TIME { get; set; }
    
        public virtual BEACHED BEACHED { get; set; }
        public virtual IN_HOUSE_TECHNOLOGY IN_HOUSE_TECHNOLOGY { get; set; }
    }
}
