//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_HOUSE_TECHNOLOGY
    {
        public IN_HOUSE_TECHNOLOGY()
        {
            this.BEACHED_IN_HOUSE_TECHNOLOGY = new HashSet<BEACHED_IN_HOUSE_TECHNOLOGY>();
        }
    
        public int TECH_ID { get; set; }
        public string TECH_NAME { get; set; }
    
        public virtual ICollection<BEACHED_IN_HOUSE_TECHNOLOGY> BEACHED_IN_HOUSE_TECHNOLOGY { get; set; }
    }
}
