//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWatchCSVExtractor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LPPEntities : DbContext
    {
        public LPPEntities()
            : base("name=LPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDITIONAL_LANGUAGE> ADDITIONAL_LANGUAGE { get; set; }
        public virtual DbSet<ADDITIONAL_TECHNOLOGY> ADDITIONAL_TECHNOLOGY { get; set; }
        public virtual DbSet<BEACHED> BEACHEDs { get; set; }
        public virtual DbSet<BEACHED_ADDITIONAL_TECHNOLOGY> BEACHED_ADDITIONAL_TECHNOLOGY { get; set; }
        public virtual DbSet<BEACHED_IN_HOUSE_TECHNOLOGY> BEACHED_IN_HOUSE_TECHNOLOGY { get; set; }
        public virtual DbSet<BEACHED_LANGUAGE> BEACHED_LANGUAGE { get; set; }
        public virtual DbSet<IN_HOUSE_TECHNOLOGY> IN_HOUSE_TECHNOLOGY { get; set; }
    
        public virtual ObjectResult<SELECT_BY_NAME_Result> SELECT_BY_NAME(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SELECT_BY_NAME_Result>("SELECT_BY_NAME", nameParameter);
        }
    }
}
