-- USEFUL COMMANDS

DROP TABLE BEACHED_IN_HOUSE_TECHNOLOGY;
DROP TABLE BEACHED_ADDITIONAL_TECHNOLOGY;
DROP TABLE BEACHED_LANGUAGE;
DROP TABLE BEACHED;
DROP TABLE IN_HOUSE_TECHNOLOGY;
DROP TABLE ADDITIONAL_TECHNOLOGY;
DROP TABLE ADDITIONAL_LANGUAGE;
SELECT * FROM BEACHED;
SELECT * FROM IN_HOUSE_TECHNOLOGY;
SELECT * FROM ADDITIONAL_TECHNOLOGY;
SELECT * FROM ADDITIONAL_LANGUAGE;
SELECT * FROM BEACHED_IN_HOUSE_TECHNOLOGY;
SELECT * FROM BEACHED_ADDITIONAL_TECHNOLOGY;
SELECT * FROM BEACHED_LANGUAGE;
EXEC SELECT_BY_NAME '';
EXEC SELECT_BY_SKILL '';
EXEC SELECT_BY_LANGUAGE '';





CREATE TABLE BEACHED
(
  BEACHED_ID BIGINT PRIMARY KEY,
  FULL_NAME VARCHAR(100) NOT NULL,
  STREAM VARCHAR(50) NOT NULL,
  ACADEMY VARCHAR(50) NOT NULL,
  PREV_PLACEMENT VARCHAR(100),
  PREV_JOB_TITLE VARCHAR(100),
  AVAILABLE TINYINT
);

CREATE TABLE IN_HOUSE_TECHNOLOGY
(
  TECH_ID INT IDENTITY(1,1) PRIMARY KEY,
  TECH_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE ADDITIONAL_TECHNOLOGY
(
  TECH_ID INT IDENTITY(1,1) PRIMARY KEY,
  TECH_NAME VARCHAR(100) UNIQUE
);

CREATE TABLE ADDITIONAL_LANGUAGE
(
  LANG_ID INT IDENTITY(1,1) PRIMARY KEY,
  LANG_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BEACHED_IN_HOUSE_TECHNOLOGY
(
  BIHT_ID INT IDENTITY(1,1) PRIMARY KEY,
  BEACHED_ID BIGINT NOT NULL REFERENCES BEACHED(BEACHED_ID),
  TECH_ID INT NOT NULL REFERENCES IN_HOUSE_TECHNOLOGY(TECH_ID),
  TECH_TIME TINYINT NOT NULL
);

CREATE TABLE BEACHED_ADDITIONAL_TECHNOLOGY
(
  BAT_ID INT IDENTITY(1,1) PRIMARY KEY,
  BEACHED_ID BIGINT NOT NULL REFERENCES BEACHED(BEACHED_ID),
  TECH_ID INT NOT NULL REFERENCES ADDITIONAL_TECHNOLOGY(TECH_ID),
  TECH_TIME TINYINT NOT NULL
);

CREATE TABLE BEACHED_LANGUAGE
(
  BL_ID INT NOT NULL PRIMARY KEY,
  BEACHED_ID BIGINT NOT NULL REFERENCES BEACHED(BEACHED_ID),
  LANG_ID INT NOT NULL REFERENCES ADDITIONAL_LANGUAGE(LANG_ID),
  FLUENCY TINYINT NOT NULL
);

-- DUMMY DATA

INSERT INTO BEACHED VALUES (
1,'John Smith', 'Technical', 'London', 'Lloyds', 'Java Developer', 1
);
INSERT INTO BEACHED VALUES (
2,'Jane Doe', 'Business', 'Leeds', NULL, NULL, 1
);
INSERT INTO BEACHED VALUES (
3,'Joe Bloggs', 'Technical', 'London', 'Barclays', 'Sys Admin', 1
);
INSERT INTO BEACHED VALUES (
4,'Dwayne Dibley', 'Business', 'Glasgow', 'RBS', 'PMO', 1
);

INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'Pro Skills'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'SQL'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'Excel'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'UNIX'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'FIA'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'ITIL'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'Java'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'.NET'
);
INSERT INTO IN_HOUSE_TECHNOLOGY VALUES (
'Murex'
);

INSERT INTO ADDITIONAL_TECHNOLOGY VALUES (
'Github'
);
INSERT INTO ADDITIONAL_TECHNOLOGY VALUES (
'Scala'
);
INSERT INTO ADDITIONAL_TECHNOLOGY VALUES (
'Project Management'
);
INSERT INTO ADDITIONAL_TECHNOLOGY VALUES (
'Python'
);

INSERT INTO ADDITIONAL_LANGUAGE VALUES (
'French'
);
INSERT INTO ADDITIONAL_LANGUAGE VALUES (
'Spanish'
);
INSERT INTO ADDITIONAL_LANGUAGE VALUES (
'German'
);
INSERT INTO ADDITIONAL_LANGUAGE VALUES (
'Mandarin'
);
INSERT INTO ADDITIONAL_LANGUAGE VALUES (
'Cantonese'
);

INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
1, 1, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
1, 2, 12
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
1, 3, 2
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
1, 4, 12
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
1, 7, 12
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
3, 1, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
3, 2, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
3, 3, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
3, 4, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
3, 8, 6
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
4, 1, 1
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
4, 2, 4
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
4, 3, 1
);
INSERT INTO BEACHED_IN_HOUSE_TECHNOLOGY VALUES (
4, 5, 8
);

INSERT INTO BEACHED_ADDITIONAL_TECHNOLOGY VALUES (
1, 1, 4
);
INSERT INTO BEACHED_ADDITIONAL_TECHNOLOGY VALUES (
2, 3, 12
);
INSERT INTO BEACHED_ADDITIONAL_TECHNOLOGY VALUES (
4, 3, 6
);
INSERT INTO BEACHED_ADDITIONAL_TECHNOLOGY VALUES (
4, 4, 6
);

INSERT INTO BEACHED_LANGUAGE VALUES (
1, 1, 1, 3
);
INSERT INTO BEACHED_LANGUAGE VALUES (
2, 1, 2, 8
);
INSERT INTO BEACHED_LANGUAGE VALUES (
3, 2, 3, 10
);
INSERT INTO BEACHED_LANGUAGE VALUES (
4, 3, 4, 8
);
INSERT INTO BEACHED_LANGUAGE VALUES (
5, 3, 5, 8
);

